version: '3.9'

services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/sre_db
    depends_on:
      - mongodb
    networks:
      - net

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    networks:
      - net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alerts.yml:/etc/prometheus/alerts.yml
    ports:
      - "9090:9090"
    networks:
      - net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - net
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:

networks:
  net:
    driver: bridge

